create table if not exists public.board_votes (
  id bigint generated by default as identity primary key,
  board_id integer not null check (board_id between 1 and 14),
  voter_id text not null,
  created_at timestamptz not null default now(),
  unique (board_id, voter_id)
);

alter table public.board_votes enable row level security;

create policy "public_can_read_votes"
on public.board_votes
for select
to anon, authenticated
using (true);

create policy "public_can_insert_votes"
on public.board_votes
for insert
to anon, authenticated
with check (board_id between 1 and 14 and length(voter_id) between 8 and 100);

create policy "public_can_delete_own_browser_vote"
on public.board_votes
for delete
to anon, authenticated
using (length(voter_id) between 8 and 100);

create index if not exists board_votes_board_id_idx on public.board_votes(board_id);

-- ============================================================
-- Painel administrativo (admin.html): tapetes gerenciáveis,
-- lista de administradores e imagens no Storage.
-- ============================================================

create table if not exists public.boards (
  id integer generated by default as identity primary key,
  title text not null check (length(trim(title)) between 1 and 80),
  image_url text not null check (length(image_url) between 1 and 500),
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Semeia os 14 tapetes originais servidos da pasta images/
insert into public.boards (id, title, image_url, position)
select i, 'Tapete cozinha ' || lpad(i::text, 2, '0'), 'images/prancha-' || lpad(i::text, 2, '0') || '.jpg', i
from generate_series(1, 14) as i
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.boards', 'id'), greatest((select max(id) from public.boards), 1));

create or replace function public.set_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists boards_set_updated_at on public.boards;
create trigger boards_set_updated_at before update on public.boards for each row execute function public.set_updated_at();

-- E-mails autorizados a usar o painel (login via Supabase Auth)
create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);
insert into public.admin_users (email) values ('gutopc@gmail.com') on conflict do nothing;
alter table public.admin_users enable row level security;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.boards enable row level security;
create policy "public_can_read_active_boards" on public.boards
  for select to anon, authenticated using (active or public.is_admin());
create policy "admin_can_insert_boards" on public.boards
  for insert to authenticated with check (public.is_admin());
create policy "admin_can_update_boards" on public.boards
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admin_can_delete_boards" on public.boards
  for delete to authenticated using (public.is_admin());

-- Votos passam a referenciar a tabela de tapetes (excluir tapete apaga os votos)
alter table public.board_votes drop constraint if exists board_votes_board_id_check;
alter table public.board_votes
  add constraint board_votes_board_id_fkey foreign key (board_id) references public.boards(id) on delete cascade;
drop policy if exists "public_can_insert_votes" on public.board_votes;
create policy "public_can_insert_votes" on public.board_votes
  for insert to anon, authenticated
  with check (
    length(voter_id) between 8 and 100
    and exists (select 1 from public.boards b where b.id = board_id and b.active)
  );
create policy "admin_can_delete_votes" on public.board_votes
  for delete to authenticated using (public.is_admin());

-- Bucket público para as imagens enviadas pelo painel
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('poll-images', 'poll-images', true, 8388608, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
create policy "public_can_read_poll_images" on storage.objects
  for select to anon, authenticated using (bucket_id = 'poll-images');
create policy "admin_can_upload_poll_images" on storage.objects
  for insert to authenticated with check (bucket_id = 'poll-images' and public.is_admin());
create policy "admin_can_update_poll_images" on storage.objects
  for update to authenticated using (bucket_id = 'poll-images' and public.is_admin());
create policy "admin_can_delete_poll_images" on storage.objects
  for delete to authenticated using (bucket_id = 'poll-images' and public.is_admin());
