create table if not exists public.board_votes (
  id bigint generated by default as identity primary key,
  board_id integer not null check (board_id between 1 and 14),
  voter_id text not null,
  created_at timestamptz not null default now(),
  unique (board_id, voter_id)
);

alter table public.board_votes enable row level security;

create policy "public_can_read_votes"
on public.board_votes
for select
to anon, authenticated
using (true);

create policy "public_can_insert_votes"
on public.board_votes
for insert
to anon, authenticated
with check (board_id between 1 and 14 and length(voter_id) between 8 and 100);

create policy "public_can_delete_own_browser_vote"
on public.board_votes
for delete
to anon, authenticated
using (length(voter_id) between 8 and 100);

create index if not exists board_votes_board_id_idx on public.board_votes(board_id);
